name: Main Pipeline

on:
  workflow_call:
    inputs:
      username:
        description: 'The user to greet'
        required: false
        default: 'Mona'
        type: string
      environment:
        description: 'Target environment (one of: staging, production, dev, qa)'
        required: false
        default: 'dev'
        type: string
      deploy-flag:
        description: 'Run deployment?'
        required: false
        type: boolean
        default: false
  workflow_dispatch:
    inputs:
      username:
        description: 'The user to greet'
        required: false
        default: 'Mona'
        type: string
      environment:
        description: 'Target environment (one of: staging, production, dev, qa)'
        required: false
        default: 'dev'
        type: string
      deploy-flag:
        description: 'Run deployment?'
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Show inputs
        run: |
          echo "username=${{ inputs.username }}"
          echo "environment=${{ inputs.environment }}"
          echo "deploy=${{ inputs.deploy-flag }}"
