name: Reusable Build

on:
  workflow_call:
  inputs:
    username:
      description: 'The user to greet'
      required: true
      default: 'Mona'
      type: string

    environment:
      description: 'Target environment'
      required: true
      type: choice
      options:
        - staging
        - production
        - dev
        - qa

    deploy-flag:
      description: 'Run deployment?'
      required: false
      type: boolean
      default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          echo "Building application..."
          echo "Build completed!"

      - name: tes
        run: echo "test is done"

      - name: deploy
        run: echo "code is deployed"
