name: Reusable Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          echo "Building application..."
          echo "Build completed!"

      - name: tes
        run: echo "test is done"

      - name: deploy
        runL echo "code is deployed"
